.gitignore
lib/game.rb
lib/stat_tracker.rb
runner.rb
test/game_test.rb
test/stat_tracker_test.rb
test/test_helper.rb

- add class file structure
- add progress on iteration 1

Add initial work on iteration 1

---

lib/stat_tracker.rb
test/stat_tracker_test.rb

Add stat tracker setup
all tests passing.

Stat tracker setup

---

lib/game.rb
lib/game_manager.rb
test/game_manager_test.rb
test/game_test.rb

- add tests for Game & GameManager
- add Game class passing test
- add GameManager with `all` method to create game objects & add passing tests

Add Game & GameManager classes

---

data/teams.csv
lib/stat_tracker.rb
lib/team.rb
lib/team_manager.rb
test/stat_tracker_test.rb
test/team_manager_test.rb
test/team_test.rb

Add team manager and team classes.
All tests passing.

Team manager

---

lib/game_teams.rb
lib/game_teams_manager.rb
test/game_teams_manager_test.rb
test/game_teams_test.rb

This branch:
1. creates the GameTeam
2. creates the GameTeamManager
3. all tests passing.

Gamesteams

---

lib/team_manager.rb
test/team_manager_test.rb

Fix variable names for consistency across project.
All tests pass.

Change @teams_attributes to @teams_data

---

lib/game.rb
lib/game_manager.rb
test/game_manager_test.rb
test/game_test.rb

Add game statistics methods with passing tests.

Game statistics

---

lib/team.rb
lib/team_manager.rb
test/team_manager_test.rb

This branch:
-writes team_info method in TeamManager
-all tests passing.

Test and code team_info

---

lib/game_teams_manager.rb
lib/stat_tracker.rb
lib/team_manager.rb
test/game_teams_manager_test.rb
test/stat_tracker_test.rb
test/team_manager_test.rb

This branch:
-Codes best offense in stat tracker with all accompanying helper methods
-all tests passing.

League statistics

---

lib/game.rb
lib/game_manager.rb
lib/game_teams.rb
lib/game_teams_manager.rb
lib/helper.rb
lib/stat_tracker.rb
lib/team.rb
lib/team_manager.rb
test/game_manager_test.rb
test/game_teams_manager_test.rb
test/game_teams_test.rb
test/game_test.rb
test/stat_tracker_test.rb
test/team_manager_test.rb
test/team_test.rb

- Revamp Manager classes' `all` methods to reduce redundant code
- Update tests to match new `all` method structure
- Add parent/child accessors to all classes' initializations
- Delete unnecessary class/test files from initial planning
- All tests are passing with 100% test coverage
- Rake run time is currently >50 seconds, we may want to explore using fixture files and/or mocks & stubs

Update CSV management & stat_tracker

---

lib/game.rb
lib/game_manager.rb
lib/game_teams_manager.rb
lib/stat_tracker.rb
lib/team_manager.rb
test/game_teams_manager_test.rb
test/game_test.rb

Explained changed on our Oct 29 morning call
- update tests to reflect refactor plans
- move game object logic to game class
- add team_name lookup method to team_manager to use in stat_tracker
- refactor game_teams best_offense method & create avg_goals_by_team helper

Refactor Game class & stat_tracker clean-up

---

lib/game.rb
lib/game_manager.rb
lib/game_teams.rb
lib/game_teams_manager.rb
lib/stat_tracker.rb
lib/team.rb
lib/team_manager.rb
test/game_manager_test.rb
test/game_teams_manager_test.rb
test/game_teams_test.rb
test/game_test.rb
test/stat_tracker_test.rb
test/team_manager_test.rb
test/team_test.rb

- add tests & methods for all league statistics to game_teams_manager & stat_tracker
- removed earlier attempt at parent/child connections to resolve broken test functionality...we can dig into that in refactor/i3!

League stats & clean up

---

lib/game_manager.rb
lib/game_teams_manager.rb
lib/stat_tracker.rb
test/game_manager_test.rb
test/game_teams_manager_test.rb
test/stat_tracker_test.rb

Incomplete seasons statistics. All tests passing

Season statistics

---

lib/game_teams_manager.rb
lib/stat_tracker.rb
test/game_teams_manager_test.rb
test/stat_tracker_test.rb

Incomplete season stats. Handing off driver/Navigator

Season stats

---

lib/game.rb
lib/game_manager.rb
lib/stat_tracker.rb
lib/team_manager.rb
test/game_manager_test.rb
test/game_test.rb
test/stat_tracker_test.rb
test/team_manager_test.rb

This branch:
-Codes best and worst season
-codes average win percentage
-codes most and fewest goals scored
-all tests passing.

Team stats

---

lib/game_manager.rb
lib/stat_tracker.rb
lib/team_manager.rb
test/game_manager_test.rb
test/stat_tracker_test.rb
test/team_manager_test.rb

This branch:
-Adds favorite opponent
-adds rival
-all tests passing.

Favorite opponent

---

lib/game_teams.rb
lib/game_teams_manager.rb
test/game_teams_manager_test.rb
test/game_teams_test.rb

- rename variables for clarity (change block variable `game` to `game_team` throughout to differentiate from game_manager iterations)
- extract boolean logic from game_teams_manager to game_team class
- update find_game_teams logic for the `else` branch to return all `game_teams` instead of `@game_teams`

GameTeams minor refactor & clean up

---

lib/game.rb
lib/game_manager.rb
lib/game_teams_manager.rb
lib/hashable.rb
lib/mathable.rb
test/game_teams_manager_test.rb
test/game_test.rb

- Refactor game_teams to remove `count_games` method (test deleted)
- Refactor game_teams avg_goals method chain to use `sub_hash_counter`
- Add helper methods to game class to abstract logic from game_manager
- Adjust blocks to one line format where possible
- Add `mathable` and `hashable` modules for team consideration
- Implement percentage calculations from `mathable` module
All tests passing. 100% SimpleCov coverage and spec harness runtime at 1.9s.

Refactor low efficiency methods & add tentative modules

---

lib/game_teams.rb
lib/game_teams_manager.rb
test/game_teams_test.rb

- remove unnecessary instance variables from `game_teams` helper methods
- add `check(home or away)` method to `game_teams` to extract logic from manager (class now under 150 lines)
- add corresponding tests for `check(home_or_away)`

Extract logic from manager to game_teams

---

lib/game_manager.rb
test/game_manager_test.rb

- Update simple game_manager blocks to match one-line preference
- Fix most/fewest goals methods placement of `<=` /  `>=` to ensure last line of guard clause is test-covered

Fix test coverage & update game_manager block format

---

lib/game_manager.rb
lib/game_teams_manager.rb
lib/supportable.rb

Adds `min_or_max` module implemented in `game_teams_manager` and `game_manager`
all tests passing.

Add supportable module implementation
